### ISSUE TITLE
[バグ]Google Analytics がちゃんと動作していない問題

### ISSUE THREAD

**Issue by h-yoshikawa0724** [h-yoshikawa0724/jigsaw-like-puzzle#17]
## 期待する動作
アクセスデータが、Google Analytics で確認できる

## 不具合内容
アクセスがあるはずなのに、Google Analytics にデータが何も来ていない

## 再現方法
Google Analytics のコンソールを確認

**Comment by h-yoshikawa0724** [comment]
数日たってもデータが表示されないため、まだ必要な要件を満たしていない可能性。

どうも Firebase SDK を読み込み後に`firebase.analytics()`をやらないといけなそう。
（ Firebase コンソールから確認できる SDK Snippet で CDN の場合のみその記述があった）

```html
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.14.5/firebase-app.js"></script>

<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="https://www.gstatic.com/firebasejs/7.14.5/firebase-analytics.js"></script>

<script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    ...※省略
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();　←これ
</script>
```
また、予約済み URL から SDK を読み込みの場合、通常のローカルサーバ（ yarn start ）では読み込むことができないため Warning が出るのが気になった（ Hostring 環境にあるファイルを読み込むもののため）
ただ、`firebase serve` でのローカルサーバでは有効らしい。

結局、`firebase` SDK ライブラリを入れて、初期化用のファイルを作り、最初に`firebase.analytics()`を実行するような形にすることにした。

**Comment by h-yoshikawa0724** [comment]
これでも`firebase.analytics()`やってる
https://stackoverflow.com/questions/58483428/google-analytics-on-my-react-app-with-firebase-sdk

**Comment by h-yoshikawa0724** [comment]
2020/5/28 14時頃、Chrome拡張のオプトアウトアドオンを一時的に無効にしてアクセスしたところ、リアルタイムアクセスに反映されたことを確認。
![firebase-dashboard](https://user-images.githubusercontent.com/43331308/83103710-33cfaf00-a0f2-11ea-8899-c9e51eb0783f.png)

このあと、レポート表示まで確認できたら Close とする。

**Comment by h-yoshikawa0724** [comment]
同日、17時頃。無事にレポート表示を確認。
![firebase-dashboard](https://user-images.githubusercontent.com/43331308/83111856-2de0ca80-a100-11ea-84cd-07f45d018064.png)

**Comment by h-yoshikawa44** [comment]
アプデ系のコミットは、ブランチ名の Issue 番号間違えていたやつ。
